INSERT INTO SSUSER (SSUSER_USERID,SSUSER_USERNAME,SSUSER_PWD) VALUES('ADMIN','Administrator1','admin');
INSERT INTO SSUSER (SSUSER_USERID,SSUSER_USERNAME,SSUSER_PWD) VALUES('ADMIN1','Administrator1','admin');
INSERT INTO SSUSER (SSUSER_USERID,SSUSER_USERNAME,SSUSER_PWD) VALUES('ADMIN2','Administrator2','admin');
INSERT INTO SSUSER (SSUSER_USERID,SSUSER_USERNAME,SSUSER_PWD) VALUES('ADMIN3','Administrator3','admin');
INSERT INTO SSUSER (SSUSER_USERID,SSUSER_USERNAME,SSUSER_PWD) VALUES('ADMIN4','Administrator4','admin');