CREATE TABLE NMCOMS (
	NMCOMS_UUID 			VARCHAR(36)  		DEFAULT '' NOT NULL,
	NMCOMS_CREATEDT 		DATETIME 			DEFAULT '1900-01-01',
	NMCOMS_CREATEBY         VARCHAR(36)         DEFAULT '',
	NMCOMS_FLAG             VARCHAR(36)         DEFAULT '',
	NMCOMS_COMID            VARCHAR(100)        DEFAULT '',
	NMCOMS_DBTYPE           INT                 DEFAULT 0,
	NMCOMS_DBSERVER         VARCHAR(100)        DEFAULT '',
	NMCOMS_DBNAME           VARCHAR(30)         DEFAULT '',
	NMCOMS_DBPORT           VARCHAR(100)        DEFAULT '',
	NMCOMS_DBUSER           VARCHAR(100)        DEFAULT '',
	NMCOMS_DBPWD            VARCHAR(100)        DEFAULT '',
	PRIMARY KEY (NMCOMS_UUID)
);