CREATE TABLE SSUSER (
	SSUSER_USERID 			VARCHAR(36)  		DEFAULT ''	NOT NULL,
	SSUSER_USERNAME         VARCHAR(60)         DEFAULT '',
	SSUSER_PWD              VARCHAR(36)         DEFAULT '',
	SSUSER_ENTITYID         VARCHAR(36)         DEFAULT '',
	PRIMARY KEY (SSUSER_USERID)
);